---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  molecule-centos7:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest

  molecule-centos8:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos8:latest

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@56310d70ae8fd21afec8d4307d2d9ab6c15e7c5d

  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@665205c3255fcf157ef8dc9a40d527fe025a4bc8
        with:
          config_file: .yamllint
